### ISSUE TITLE
Error in VS for UWP app

### ISSUE THREAD

**Issue by shllybkwrm** [mtaulty/SimpleUwpTwoWayComms#1]
Hi, I wanted to try this project out but I'm running into an error on the UWP side...

![image](https://user-images.githubusercontent.com/2496635/37425553-22a8e0e4-279a-11e8-988f-e6d5e82e0a31.png)

This is the same whether I run with or without debugging.

I assumed the project would already be configured, but are there some startup steps I need to go through first?

**Comment by mtaulty** [comment]
Hi - it sounds like Visual Studio has the library project set as the start up project so it is trying to run a library rather than an application which consumes the library. Use the right mouse menu to set the application project as the startup project and then hit F5. Hope that helps.

**Comment by shllybkwrm** [comment]
Thanks, that worked!  Sorry to bother you about such a small issue, I never seem to know what I'm doing with Visual Studio.
